import "./global.css";
import NavBar from "@/components/Navbar";

export const metadata = {
  title: "App",
  description: "Generated by Next.js",
  keywords: ["nextjs", "marissa"],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        <main className="flex justify-center items-center">{children}</main>
      </body>
    </html>
  );
}
